version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages: 
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test 
      - run : 
          name : Run build
          command: npm run build 
      - persist_to_workspace:
          root: ~/project
          paths:
            - .